// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plhezahvxueojrospexg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsaGV6YWh2eHVlb2pyb3NwZXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NDQxNzYsImV4cCI6MjA3MTMyMDE3Nn0.1jm6hL-KojdtPqfUZPAY5KgQCYTfnzVqUwP8jh8q3SI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});